Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VNGraphiteCore.Models;
using VNGraphiteCore.RestApi;

namespace VNGraphiteCore.Controllers
{
    [Route("tin-tuc")]
    public class NewsController : BaseController
    {
        private readonly Random rnd = new Random();
        private readonly IPostRestClient m_postClient;

        public NewsController(IPostRestClient postClient)
        {
            m_postClient = postClient;
        }

        public IActionResult Index()
        {
            var categories = m_postClient.ListCategory();
            //var categories = SampleData.CategoryData;
            ViewData["Category"] = categories.ToDictionary(k => k.Id, v => v.Name);
            ViewData["IsMobile"] = RequestExtensions.IsMobileBrowser(Request);

            var data = m_postClient.ListPost();
            //var data = SampleData.NewsData;
            var dictNewsData = data.GroupBy(x => x.CategoryId).ToDictionary(k => k.Key, v => v.OrderByDescending(x => x.Published_At).Take(3).ToList());

            return View(dictNewsData);
        }

        [Route("/tin-tuc/chi-tiet/{slug?}")]
        public IActionResult Detail(string slug = "")
        {
            if (String.IsNullOrEmpty(slug))
            {
                return View("Error");
            }
            //Post newsDetail = SampleData.NewsData.FirstOrDefault(x => x.Slug.Contains(slug));
            var newsDetail = m_postClient.GetPost(slug);

            if (newsDetail == null)
            {
                return View("Error");
            }

            if (newsDetail.PostItems != null && newsDetail.PostItems.Any())
                newsDetail.PostItems = newsDetail.PostItems.OrderBy(x => x.Id).ToList();


            // Giả lập số lượng view
            var data = m_postClient.ListPost();
            //List<Post> data = SampleData.NewsData.ToList();
            foreach (var news in data)
            {
                news.ViewCount = rnd.Next(1, 100000);
            }

            //ViewData["SameData"] = data;
            ViewData["SameData"] = data.Where(x => x.CategoryId == newsDetail.CategoryId).ToList();

            var detailVM = new NewsDetailVM { 
                NewsDetail = newsDetail,
                PopularNews = data.OrderByDescending(x => x.ViewCount).Take(2).ToList()
            };

            return View(detailVM);
        }

        [Route("/tin-tuc/{categoryId}")]
        public IActionResult NewsByCategory(int categoryId)
        {
            var result = m_postClient.ListPostByCategory(categoryId);

            return View(result);
        }
    }
}

Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace VNGraphiteCore.Controllers
{
    [Route("doi-ngu")]
    public class TeamController : BaseController
    {
        public IActionResult Index()
        {
            var isMobile = (bool)ViewData["IsMobile"];

            if (isMobile)
            {
                return View("Index.Mobile");
            }

            return View();
        }
    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="~/dist/Post_Images/favicon.png">

    <link href="~/dist/index.bundle.css" rel="stylesheet" />
    <link href="~/dist/adminlte.bundle.css" rel="stylesheet" />
    
    <link href="https://fonts.googleapis.com/css?family=Bai+Jamjuree&display=swap" rel="stylesheet">
</head>
<body id="main">

    <partial name="_AdminMenu" />

    <div class="container-fluid body-content p-0">
        @RenderBody()
        <partial name="_Footer" />
    </div>

    <script src="~/dist/index.bundle.js"></script>
    
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_AdminMenu.cshtml
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="../../index3.html" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        @*<img src="../../dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">*@
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        @*<img src="../../dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">*@
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        @*<img src="../../dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">*@
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>

Views/Shared/_Footer.cshtml
<footer>
    <div class="container pt-4 pb-4">
        <div class="row">
            <div class="col-8">
                <partial name="_Logo" />
            </div>
            <div class="col-4">
                <span class="text-white small">
                    02437 833 692
                </span><br />
                <span class="text-white small">
                    lienhe@vietnamgraphite.com
                </span><br />
                <span class="text-white small">
                    Tầng 15, Tòa nhà Việt Á, Phố Duy Tân, Cầu Giấy, Hà Nội
                </span>
            </div>
        </div>
        <div class="row pt-3">
            <div class="col-8">
                <span class="text-white small">Copyright © 2018 VIETNAMGRAPHITE. All Right Reserved.</span>
            </div>
            <div class="col-4">
                <a class="text-white" href="#"><i class="fab fa-facebook-square"></i></a>
                <a class="text-white pl-4" href="#"><i class="fab fa-youtube"></i></a>
                <a class="text-white pl-4" href="#"><i class="fab fa-instagram"></i></a>
            </div>
        </div>
    </div>
</footer>

Views/Shared/_FooterMobile.cshtml
<footer>
    <div class="container pt-4 pb-4">
        <div class="row">
            <div class="col-12">
                <partial name="_Logo" />
            </div>
            <div class="col-12">
                <span class="text-white small">
                    02437 833 692
                </span><br />
                <span class="text-white small">
                    lienhe@vietnamgraphite.com
                </span><br />
                <span class="text-white small">
                    Tầng 15, Tòa nhà Việt Á, Phố Duy Tân, Cầu Giấy, Hà Nội
                </span>
            </div>
        </div>
    </div>
</footer>

Views/Shared/_ImageSlide.cshtml
<!-- ======== slide Post_Images ======== -->
<div id="highlighted">
    <!-- Showshow - Slider Revolution see: plugins/slider-revolution/examples&sources for help invoke using data-toggle="slider-rev" options can be passed to the slider via HTML5 data- ie. data-startwidth="960" -->
    <div class="slider-wrapper rev_slider_wrapper fullscreen-container bg-black" data-page-class="slider-appstrap-theme">
        <div class="rev_slider fullscreenbanner" data-toggle="slider-rev" data-settings='{"startwidth":1100, "startheight":620, "delay":10000}'>
            <ul class="list-group">
                <!-- SLIDE 1 -->
                <li class="slide overlay overlay-op-4 overlay-gradient" data-transition="fadethroughdark" data-slotamount="7" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="assets/img/slides/app_bg.jpg" data-rotate="0" data-saveperformance="off" data-title="Slide" data-link="shop-list.html">
                    <img src="~/dist/Post_Images/can-cau.jpg" data-lazyload="~/dist/Post_Images/can-cau.jpg" alt="background image" data-bgposition="center top" data-bgfit="cover" data-bgparallax="off" class="rev-slidebg" data-no-retina />
                    <!-- SLIDE 1 Content-->
                    <div class="slide-content container" style="z-index: 10;">
                    </div>
                </li>
            </ul>
            <div class="tp-bannertimer tp-bottom"></div>
        </div>
        <!--end of tp-banner-->
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="~/dist/Post_Images/favicon.png">

    <link href="~/dist/index.bundle.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Bai+Jamjuree&display=swap" rel="stylesheet">
</head>
<body id="main">
    @{ 
        var isMobile = ViewData["IsMobile"] != null && (bool)ViewData["IsMobile"] == true;
    }
    <partial name="_Menu" model="@isMobile" />

    <div class="container-fluid body-content p-0">
        @RenderBody()
        @if (isMobile)
        {
            <partial name="_FooterMobile" />
        }
        else
        {
            <partial name="_Footer" />
        }

    </div>

    <script src="~/dist/index.bundle.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Menu.cshtml
@model bool
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <div class="container">
        <a class="navbar-brand" href="@Url.Action("Index", "Home")">
            <partial name="_Logo" />
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <!-- class menu doc mobile: navbar-nav mr-auto-->
            <ul class="@(Model ? "navbar-nav mr-auto" : "nav")">
                <li class="nav-item font-weight-bold active">
                    <a class="nav-link text-uppercase text-dark" href="@Url.Action("Index", "Home")">Trang chủ</a>
                </li>
                <li class="nav-item font-weight-bold dropdown">
                    <a class="nav-link text-uppercase text-dark dropdown-toggle" id="mnuIntro" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Giới thiệu</a>
                    <div class="dropdown-menu" role="menu" aria-labelledby="mnuIntro">
                        <a class="dropdown-item text-uppercase" href="@Url.Action("Index", "GeneralInfo", new { moduleName = "" })">THÔNG TIN CHUNG</a>
                        <a class="dropdown-item text-uppercase" data-link="graphite-map" href="@Url.Action("Index", "GeneralInfo", new { moduleName = "graphite-map" })">MỎ GRAPHITE</a>
                        <a class="dropdown-item text-uppercase" data-link="graphite-factory" href="@Url.Action("Index", "GeneralInfo", new { moduleName = "graphite-factory" })">NHÀ MÁY CHẾ BIẾN</a>
                        <a class="dropdown-item text-uppercase" data-link="graphite-company" href="@Url.Action("Index", "GeneralInfo", new { moduleName = "graphite-company" })">NGÀNH NGHỀ HOẠT ĐỘNG</a>
                        <a class="dropdown-item text-uppercase" href="@Url.Action("Index", "Team")">ĐỘI NGŨ</a>
                    </div>
                </li>
                <li class="nav-item font-weight-bold">
                    <a class="nav-link text-uppercase text-dark" href="@Url.Action("Index", "Product")">Sản phẩm</a>
                </li>
                <li class="nav-item font-weight-bold">
                    <a class="nav-link text-uppercase text-dark" href="@Url.Action("Index", "News")">Tin tức</a>
                </li>
                <li class="nav-item font-weight-bold">
                    <a class="nav-link text-uppercase text-dark" href="@Url.Action("Index", "Partner")">Đối tác</a>
                </li>
                <li class="nav-item font-weight-bold">
                    <a class="nav-link text-uppercase text-dark" href="@Url.Action("Index", "Gallery")">Hình ảnh</a>
                </li>
                <li class="nav-item font-weight-bold">
                    <a class="nav-link text-uppercase text-dark" href="@Url.Action("Index", "Contact")">Liên hệ</a>
                </li>
            </ul>
        </div>
    </div>
</nav>